FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip setuptools wheel && \
    pip install --no-cache-dir -r requirements.txt
COPY backend/ ./backend/
COPY can_layer/ ./can_layer/
COPY explainability/ ./explainability/
COPY models/ ./models/
COPY data/ ./data/
COPY services/ ./services/
COPY dataset_generator.py .
COPY .env .env

CMD ["python", "services/api_gateway/main.py"]
